# Generated by Django 4.0.6 on 2022-08-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
